package com.github.mkubasz.oodclassicalautocompleted.editor.autocomplete

internal object AutocompleteTriggerHeuristics {

    data class Decision(
        val shouldRequest: Boolean,
        val reason: Reason? = null,
    )

    enum class Reason {
        EMPTY_DOCUMENT,
        OVERSIZED_FILE,
        GENERATED_FILE,
        IMPORT_CONTEXT,
        COMMENT_CONTEXT,
        STRING_CONTEXT,
        LOW_SIGNAL_WHITESPACE,
    }

    fun evaluate(
        documentText: String,
        offset: Int,
        filePath: String?,
        maxDocumentChars: Int,
        lookbackForNonWhitespace: Int,
    ): Decision {
        if (documentText.isEmpty()) {
            return Decision(false, Reason.EMPTY_DOCUMENT)
        }
        if (documentText.length > maxDocumentChars) {
            return Decision(false, Reason.OVERSIZED_FILE)
        }
        if (isGeneratedFile(filePath, documentText)) {
            return Decision(false, Reason.GENERATED_FILE)
        }
        if (isImportContext(documentText, offset)) {
            return Decision(false, Reason.IMPORT_CONTEXT)
        }

        return when (lexicalContextAt(documentText, offset)) {
            LexicalContext.DEFAULT -> {
                if (isLowSignalWhitespaceContext(documentText, offset, lookbackForNonWhitespace)) {
                    Decision(false, Reason.LOW_SIGNAL_WHITESPACE)
                } else {
                    Decision(true)
                }
            }

            LexicalContext.COMMENT -> Decision(false, Reason.COMMENT_CONTEXT)
            LexicalContext.STRING -> Decision(false, Reason.STRING_CONTEXT)
        }
    }

    private fun isGeneratedFile(filePath: String?, documentText: String): Boolean {
        val normalizedPath = filePath?.replace('\\', '/')?.lowercase().orEmpty()
        if (normalizedPath.contains("/generated/") ||
            normalizedPath.contains("/build/generated/") ||
            normalizedPath.contains("/target/generated-") ||
            normalizedPath.contains("/dist/generated/")
        ) {
            return true
        }

        val header = documentText
            .lineSequence()
            .take(GENERATED_HEADER_LINE_SCAN)
            .joinToString("\n")
            .lowercase()

        return ("auto-generated" in header) ||
            ("autogenerated" in header) ||
            ("@generated" in header) ||
            ("generated by" in header) ||
            ("do not edit" in header && "generated" in header)
    }

    private fun isImportContext(documentText: String, offset: Int): Boolean {
        val lineStart = documentText.lastIndexOf('\n', (offset - 1).coerceAtLeast(0)).let { it + 1 }
        val lineEnd = documentText.indexOf('\n', offset).let { if (it == -1) documentText.length else it }
        val lineText = documentText.substring(lineStart, lineEnd).trimStart()

        return lineText.startsWith("import ") ||
            lineText == "import" ||
            lineText.startsWith("from ")
    }

    private fun isLowSignalWhitespaceContext(documentText: String, offset: Int, lookbackForNonWhitespace: Int): Boolean {
        val prefix = documentText.substring(0, offset)
        val suffix = documentText.substring(offset)
        val lowSignalByWhitespace = prefix.takeLast(lookbackForNonWhitespace).isBlank() &&
            suffix.take(lookbackForNonWhitespace).isBlank()

        return lowSignalByWhitespace && !isHighSignalWhitespaceContext(prefix)
    }

    private fun isHighSignalWhitespaceContext(prefix: String): Boolean {
        if (prefix.isEmpty()) return false

        val currentLinePrefix = prefix.substringAfterLast('\n')
        if (currentLinePrefix.isBlank() && '\n' in prefix) {
            return true
        }

        val trimmedPrefix = prefix.trimEnd()
        if (trimmedPrefix.isEmpty()) return false

        return trimmedPrefix.last() in HIGH_SIGNAL_OPENINGS || trimmedPrefix.endsWith("->")
    }

    private fun lexicalContextAt(documentText: String, offset: Int): LexicalContext {
        var state = LexicalState.DEFAULT
        var lineHasOnlyWhitespace = true
        var index = 0

        while (index < offset) {
            when (state) {
                LexicalState.DEFAULT -> {
                    when {
                        documentText.startsWith("//", index) -> {
                            state = LexicalState.LINE_COMMENT
                            index += 2
                            continue
                        }

                        documentText.startsWith("/*", index) -> {
                            state = LexicalState.BLOCK_COMMENT
                            index += 2
                            continue
                        }

                        documentText.startsWith("<!--", index) -> {
                            state = LexicalState.XML_COMMENT
                            index += 4
                            continue
                        }

                        documentText.startsWith("\"\"\"", index) -> {
                            state = LexicalState.TRIPLE_DOUBLE
                            index += 3
                            lineHasOnlyWhitespace = false
                            continue
                        }

                        documentText.startsWith("'''", index) -> {
                            state = LexicalState.TRIPLE_SINGLE
                            index += 3
                            lineHasOnlyWhitespace = false
                            continue
                        }

                        documentText[index] == '"' -> {
                            state = LexicalState.DOUBLE_QUOTE
                            index++
                            lineHasOnlyWhitespace = false
                            continue
                        }

                        documentText[index] == '\'' -> {
                            state = LexicalState.SINGLE_QUOTE
                            index++
                            lineHasOnlyWhitespace = false
                            continue
                        }

                        documentText[index] == '`' -> {
                            state = LexicalState.BACKTICK
                            index++
                            lineHasOnlyWhitespace = false
                            continue
                        }

                        documentText[index] == '#' &&
                            (lineHasOnlyWhitespace || (index > 0 && documentText[index - 1].isWhitespace())) -> {
                            state = LexicalState.LINE_COMMENT
                            index++
                            continue
                        }
                    }

                    val ch = documentText[index]
                    if (ch == '\n') {
                        lineHasOnlyWhitespace = true
                    } else if (!ch.isWhitespace()) {
                        lineHasOnlyWhitespace = false
                    }
                    index++
                }

                LexicalState.LINE_COMMENT -> {
                    val ch = documentText[index]
                    index++
                    if (ch == '\n') {
                        state = LexicalState.DEFAULT
                        lineHasOnlyWhitespace = true
                    }
                }

                LexicalState.BLOCK_COMMENT -> {
                    if (documentText.startsWith("*/", index)) {
                        state = LexicalState.DEFAULT
                        index += 2
                    } else {
                        lineHasOnlyWhitespace = documentText[index] == '\n'
                        index++
                    }
                }

                LexicalState.XML_COMMENT -> {
                    if (documentText.startsWith("-->", index)) {
                        state = LexicalState.DEFAULT
                        index += 3
                    } else {
                        lineHasOnlyWhitespace = documentText[index] == '\n'
                        index++
                    }
                }

                LexicalState.SINGLE_QUOTE -> {
                    val advance = advanceString(documentText, index, '\'', offset)
                    index = advance.index
                    if (advance.closed) {
                        state = LexicalState.DEFAULT
                        lineHasOnlyWhitespace = false
                    }
                }

                LexicalState.DOUBLE_QUOTE -> {
                    val advance = advanceString(documentText, index, '"', offset)
                    index = advance.index
                    if (advance.closed) {
                        state = LexicalState.DEFAULT
                        lineHasOnlyWhitespace = false
                    }
                }

                LexicalState.BACKTICK -> {
                    val advance = advanceString(documentText, index, '`', offset)
                    index = advance.index
                    if (advance.closed) {
                        state = LexicalState.DEFAULT
                        lineHasOnlyWhitespace = false
                    }
                }

                LexicalState.TRIPLE_SINGLE -> {
                    if (documentText.startsWith("'''", index)) {
                        state = LexicalState.DEFAULT
                        index += 3
                        lineHasOnlyWhitespace = false
                    } else {
                        if (documentText[index] == '\n') {
                            lineHasOnlyWhitespace = true
                        }
                        index++
                    }
                }

                LexicalState.TRIPLE_DOUBLE -> {
                    if (documentText.startsWith("\"\"\"", index)) {
                        state = LexicalState.DEFAULT
                        index += 3
                        lineHasOnlyWhitespace = false
                    } else {
                        if (documentText[index] == '\n') {
                            lineHasOnlyWhitespace = true
                        }
                        index++
                    }
                }
            }
        }

        return when (state) {
            LexicalState.DEFAULT -> LexicalContext.DEFAULT
            LexicalState.LINE_COMMENT, LexicalState.BLOCK_COMMENT, LexicalState.XML_COMMENT -> LexicalContext.COMMENT
            LexicalState.SINGLE_QUOTE,
            LexicalState.DOUBLE_QUOTE,
            LexicalState.BACKTICK,
            LexicalState.TRIPLE_SINGLE,
            LexicalState.TRIPLE_DOUBLE -> LexicalContext.STRING
        }
    }

    private fun advanceString(documentText: String, startIndex: Int, delimiter: Char, offset: Int): StringAdvance {
        var index = startIndex
        while (index < offset) {
            val ch = documentText[index]
            if (ch == '\\') {
                index = (index + 2).coerceAtMost(offset)
                continue
            }
            index++
            if (ch == delimiter) {
                return StringAdvance(index, closed = true)
            }
        }
        return StringAdvance(index, closed = false)
    }

    private data class StringAdvance(
        val index: Int,
        val closed: Boolean,
    )

    private enum class LexicalContext {
        DEFAULT,
        COMMENT,
        STRING,
    }

    private enum class LexicalState {
        DEFAULT,
        LINE_COMMENT,
        BLOCK_COMMENT,
        XML_COMMENT,
        SINGLE_QUOTE,
        DOUBLE_QUOTE,
        BACKTICK,
        TRIPLE_SINGLE,
        TRIPLE_DOUBLE,
    }

    private const val GENERATED_HEADER_LINE_SCAN = 12
    private val HIGH_SIGNAL_OPENINGS = charArrayOf('{', '(', '[', ':', '=', ',')
}
